In [70]:
print("hello world")

hello world


In [71]:

age=int(input("enter a number"))
if age>=18:
   print("eligible to vote")
else:
    print("not eligible to vote")


not eligible to vote


In [72]:
def add_runs(score,extra_runs):
    total=score+extra_runs
    return total
print(add_runs(45,5))

50


In [73]:
def show_captain(team_data):
    print(team_data["captain_key"])
team={
    "team_name":"Mumbai Indians",
    "captain_key":"rohit sharma"
}
show_captain(team)

rohit sharma


In [74]:
def print_player(*args):
 for name in args:
    print(name)
print_player("vk","rs","ms","hp")

vk
rs
ms
hp


In [75]:
import numpy as np 
arr1=np.array([[10,20,30],[40,50,60]])
c=np.shape(arr1)
print(c)
d=np.ndim(arr1)
print(d)
e=np.size(arr1)
print(e)
print(arr1.dtype)
print(arr1.reshape(2,3))


(2, 3)
2
6
int64
[[10 20 30]
 [40 50 60]]


In [76]:
arr1=np.arange(1,13)
arr2=arr1.reshape(2,6)
print(arr2)
arr3 = arr2.ravel() #copy data
arr4=arr2.flatten()
print(arr3)
print(arr4)
arr3[0]=0
print(arr3)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  2  3  4  5  6  7  8  9 10 11 12]
[[ 0  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [77]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
shape=np.shape(arr)
print(shape)
reshape=arr.reshape(5,2)
print(reshape)

(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [78]:

arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
add=arr1+arr2
sub=arr1-arr2
multi=arr1*arr2
div=arr1/arr2
print("addition",add)
print("subtraction",sub)
print("multiplication",multi)
print("division",div)

addition [ 7  9 11 13 15]
subtraction [-5 -5 -5 -5 -5]
multiplication [ 6 14 24 36 50]
division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [79]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(arr))
print(np.square(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[ 1  4  9 16 25 36 49 64 81]


In [80]:
arr=np.array([12,14,16,18,20,22])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 12  26  42  60  80 102]
[      12      168     2688    48384   967680 21288960]


In [81]:
arr=np.random.randn(1,10)
print(np.argmin(arr))
print(np.argmax(arr))

0
2
